name: Test Job

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 3: set environment variable for workflow
    - name: Set environment variable
      id: set_archive_url
      shell: bash
      run: |
        echo "TEST_URL=s3://test/test.tar.gz" >> $GITHUB_OUTPUT