name: Test Job

outputs:
  test:
    value: ${{ steps.set.outputs.test }}

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 3: set environment variable for workflow
    - name: Set environment variable
      id: set
      shell: bash
      run: |
        echo "test=a url to save" >> $GITHUB_OUTPUT